/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tdlrxymlanvpasjbnadn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbHJ4eW1sYW52cGFzamJuYWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MzU1NTQsImV4cCI6MjA4MTExMTU1NH0.pfSqq9MjCan6jDmEhg9j40WEFFsvW-99tAI-BpjEU3A"